apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  name: upbound-bucket-02
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  forProvider:
    region: us-east-2
  providerConfigRef:
    name: default
